frr version 8.5
frr defaults traditional
hostname r1
log syslog informational
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.12.1/30
 ip ospf area 0
!
interface eth2
 ip address 10.0.13.1/30
 ip ospf area 0
 ip ospf cost 100
!
interface eth3
 ip address 192.168.1.1/24
!
interface lo
 ip address 1.1.1.1/32
 ip ospf area 0
!
router ospf
 ospf router-id 1.1.1.1
 passive-interface eth3
!
router bgp 65000
 bgp router-id 1.1.1.1
 no bgp default ipv4-unicast
 neighbor 2.2.2.2 remote-as 65000
 neighbor 2.2.2.2 update-source lo
 neighbor 3.3.3.3 remote-as 65000
 neighbor 3.3.3.3 update-source lo
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor 2.2.2.2 activate
  neighbor 2.2.2.2 next-hop-self
  neighbor 3.3.3.3 activate
  neighbor 3.3.3.3 next-hop-self
 exit-address-family
!
line vty
!
